apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: myimage=staging-docker-registry.fbox.fpt.vn/api/interval-service
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:dev-.*$
    argocd-image-updater.argoproj.io/myimage.pull-secret: secret:argocd/harbor#credential
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: ' git:secret:argocd/git-creds'
  name: staging-playos4-interval
spec:
  destination:
    namespace: demo-playos4
    server: https://staging-rancher.fbox.fpt.vn/k8s/clusters/local
  project: default
  source:
    helm:
      valueFiles:
      - values/playos4/playos4-interval/healthcheck.yaml
      - values/playos4/playos4-interval/image.yaml
      - values/playos4/playos4-interval/ingress.yaml
      - values/playos4/playos4-interval/secret.yaml
      - values/playos4/playos4-interval/strategies.yaml
      - values/playos4/playos4-interval/volume.yaml
      - values/playos4/playos4-interval/job.yaml
    path: Manifest
    repoURL: https://git.fpt.net/fpl/he-thong/test/demo-argocd/manifest.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
