healthcheck:
  livenessProbe:
    enabled: false
    httpGet:
      path: 
      port: 
    initialDelaySeconds: 
    timeoutSeconds: 
    failureThreshold: 
    successThreshold: 
    periodSeconds: 

  # Custom livenessProbe.
  customLivenessProbe: 
    tcpSocket:
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    
  # Xác định mức độ sẵn sàng. Kiểm tra xem khi nào thì app trong pod có thể nhận traffic.
  readinessProbe:
    enabled: false
    httpGet:
      path: 
      port: 
      name: 
      value: 
    initialDelaySeconds: 
    timeoutSeconds: 
    failureThreshold: 
    successThreshold: 
    periodSeconds: 

  # Custom readinessProbe
  customReadinessProbe:
    failureThreshold: 5
    successThreshold: 1
    tcpSocket:
      port: 5000
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5

  lifecycle:
    preStop:
      exec:
        command: ["sh","-c","sleep 9"]




