apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: myimage=staging-docker-registry.fbox.fpt.vn/api/cms-fptplay
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:dev-.*$
    argocd-image-updater.argoproj.io/myimage.pull-secret: secret:argocd/harbor#credential
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: ' git:secret:argocd/git-creds'
  name: staging-cms-api-notification
spec:
  destination:
    namespace: demo-cms
    server: https://staging-rancher.fbox.fpt.vn/k8s/clusters/local
  project: default
  source:
    helm:
      valueFiles:
      - values/cms/cms-api-notification/healthcheck.yaml
      - values/cms/cms-api-notification/image.yaml
      - values/cms/cms-api-notification/ingress.yaml
      - values/cms/cms-api-notification/secret.yaml
      - values/cms/cms-api-notification/strategies.yaml
      - values/cms/cms-api-notification/volume.yaml
      - values/cms/cms-api-notification/job.yaml
    path: Manifest
    repoURL: https://git.fpt.net/fpl/he-thong/test/demo-argocd/manifest.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
