{{- if .Values.externalSecret.extVault.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-{{ .Values.service.applicationName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-vault-{{ .Values.service.applicationName }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore}}
    kind: ClusterSecretStore
  target:
    name: env-{{ .Values.service.applicationName }}
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: cm-{{ .Values.service.applicationName }}
            items:
            - key: {{ .Values.configmap.key }}
  {{- if .Values.externalSecret.dataFrom.enabled }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.key }}
  {{- end }}
  {{- if .Values.externalSecret.data.enabled }}
  data:
  - secretKey: env
    remoteRef:
      key: {{ .Values.externalSecret.key }}
  {{- end }}
{{- end}}
