{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cronjob-{{ .Values.cronjob.jobName }}-{{ .Values.service.applicationName }}
  annotations:
    argocd.argoproj.io/hook: {{ .Values.cronjob.hook }}
    argocd.argoproj.io/hook-delete-policy: {{ .Values.cronjob.deleteHook }}
spec:
  template:
    spec:
      containers:
      - name: cronjob-{{ .Values.cronjob.jobName }}-{{ .Values.service.applicationName }}
        image: {{ .Values.cronjob.imageJob }}
        command:
          - /bin/sh
          - -c
          - {{ .Values.cronjob.args }}
        env:
          - name: HTTP_PROXY
            value: http://proxy.hcm.fpt.vn:80
          - name: HTTPS_PROXY
            value: http://proxy.hcm.fpt.vn:80
          - name: NO_PROXY
            value: 10.43.0.1,localhost
      restartPolicy: Never
  backoffLimit: 2
{{- end }}

