####################################################################################
ingress:
  enabled: false
  path: /
  pathType: Prefix
####################################################################################
