externalSecret:
  dataFrom:
    enabled: false
  data:
    enabled: true
  enabled: true
  vaultAddress: http://172.20.2.105:31783
  vaultPathData: k8s
  vaultVersionData: v2 
  vaultMountPathAccess: kubernetes
  vaultRoleAccess: read_env
  refreshInterval: 30s
  key: playos4-payment
