####################################################################################
# Kiểm tra khi nào pod khởi động lại bằng cách health check vào pod.
healthcheck:
  livenessProbe:
    enabled: false
    httpGet:
      path: /dev/notice/a
      port: 5000
    initialDelaySeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
    periodSeconds: 10

  # Custom livenessProbe.
  customLivenessProbe: 
    tcpSocket:
      port: 5001
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 9
    
  # Xác định mức độ sẵn sàng. Kiểm tra xem khi nào thì app trong pod có thể nhận traffic.
  readinessProbe:
    enabled: false
    httpGet:
      path: 
      port: http
      name: Host
      value: 
    initialDelaySeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 10

  # Custom readinessProbe
  customReadinessProbe:
    failureThreshold: 5
    successThreshold: 1
    tcpSocket:
      port: 5001
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 1

  lifecycle:
    preStop:
      exec:
        command: ["sh","-c","sleep 10"]
####################################################################################
